name: ui_coffe_app
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  # é€šç”¨
  hzy_common_module:
    path: ../../packages/hzy_common_module/
  google_fonts: 5.1.0
  flutter_feather_icons: 2.0.0+1
  get_it: 7.6.4

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/images/
    - assets/images/coffee/
    - assets/images/treat/
